text = input("Enter text to be analysed:\n ")
alpha1 = input("What is the first alphabet: ")
alpha2 = input("What is the second alphabet: ")
alpha3 = input("What is the third alphabet: ")
count_alpha1 = text.count(alpha1)
count_alpha2 = text.count(alpha2)
count_alpha3 = text.count(alpha3)
data = text.split(" ")

print("\n\n")
print("###########################################################################")
print("\n\n")

print(f"The number of times {alpha1} has been seen in the text is {count_alpha1}")
print(f"The number of times {alpha2} has been seen in the text is {count_alpha2}")
print(f"The number of times {alpha3} has been seen in the text is {count_alpha3}")
print(f"The number of words in the text was found to be {len(data)}")
print(f"The first and last letters of the words respectively are {text[0]} and {text[-1]}")
print(f"\nIf the order of the words were to be inverted the text looks like: \n\n{' '.join(data[::-1])}")
print(f"\nThe word python was {text.count('python')} times found in the text")
